// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oGeya3WnsoRJC1KzKAMsFn
// Component: IhRw9yiGNV_j

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: oGeya3WnsoRJC1KzKAMsFn/projectcss
import sty from "./Plasmic_124IntroductionToTheEnvironmentOfTheDay.module.css"; // plasmic-import: IhRw9yiGNV_j/css

createPlasmicElementProxy;

export type Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantMembers =
  {};
export type Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantsArgs = {};
type VariantPropType =
  keyof Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantsArgs;
export const Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantProps =
  new Array<VariantPropType>();

export type Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgsType = {};
type ArgPropType =
  keyof Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgsType;
export const Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgProps =
  new Array<ArgPropType>();

export type Plasmic_124IntroductionToTheEnvironmentOfTheDay__OverridesType = {
  root?: Flex__<"div">;
};

export interface Default_124IntroductionToTheEnvironmentOfTheDayProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_124IntroductionToTheEnvironmentOfTheDay__RenderFunc(props: {
  variants: Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantsArgs;
  args: Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgsType;
  overrides: Plasmic_124IntroductionToTheEnvironmentOfTheDay__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.root
        )}
      >
        <div className={classNames(projectcss.all, sty.freeBox__nnZWo)}>
          <div className={classNames(projectcss.all, sty.freeBox__i6KQ)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___1Y7Bm
              )}
            >
              {"\u6587\u7ae0"}
            </div>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__hijzY)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__erbmu)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"25%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              onClick={async event => {
                const $steps = {};

                $steps["goToPage"] = true
                  ? (() => {
                      const actionArgs = {
                        destination: (() => {
                          try {
                            return $ctx.config.routePrefix + "/";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToPage"] != null &&
                  typeof $steps["goToPage"] === "object" &&
                  typeof $steps["goToPage"].then === "function"
                ) {
                  $steps["goToPage"] = await $steps["goToPage"];
                }
              }}
              src={{
                src: "/plasmic/gu_lou_patient/images/资源162Xpng.png",
                fullWidth: 198,
                fullHeight: 198,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__aRs6L
              )}
            >
              {"\u9000\u51fa"}
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__gsjJo)}>
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__uuHo6)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            loading={"lazy"}
            src={{
              src: "/plasmic/gu_lou_patient/images/_560转换01Png.png",
              fullWidth: 1201,
              fullHeight: 351,
              aspectRatio: undefined
            }}
          />

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ajA71
            )}
          >
            <React.Fragment>
              <span
                className={"plasmic_default__all plasmic_default__span"}
                style={{
                  id: "ne6N8JGRae",
                  src: "康复训练",
                  dst: "rehabilitation training "
                }}
              >
                {"\u73af\u5883\u4ecb\u7ecd"}
              </span>
            </React.Fragment>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__n0U54)}>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__jssi3)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/gu_lou_patient/images/bjjpg.jpg",
                fullWidth: 611,
                fullHeight: 446,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lZq8Z
              )}
            >
              {
                "\u95e8\u8bca\u79d1\u5ba4\n\u5206\u5e03\u8868-1F\u5730\u4e0b\u8f66\u5e93\n\n1F\u5bfc\u533b\u53f0\u3001\u9f13\u697c\u5927\u836f\u5e97\u3001\u94f6\u884c\u3001\u5546\u5e97\u7b49\u975e\u533b\u7597\u670d\u52a1\u533a\u3001\u809d\u708e\u95e8\u8bca\u3001\n\u53d1\u70ed\u95e8\u8bca\u3001\u80a0\u9053\u95e8\u8bca\n\n2F\u5317\t\n\u6302\u53f7\u6536\u8d39\u3001\u95e8\u8bca\u836f\u623f\u3001\u95e8\u8bca\u68c0\u9a8c\u3001\u6362\u836f\u5ba4\n\n1\u533a\uff08\u4e1c\uff09\n\u666e\u901a\u5916\u79d1(\u809d\u80c6\u3001\u80c3\u80a0\u3001\u7532\u4e73)\u3001\u8840\u7ba1\u901a\u8def\u62a4\u7406\u95e8\u8bca\u3001\u4f24\u53e3\u62a4\u7406\u95e8\u8bca\uff08\u5916\u79d1B\u8d85\uff09\n\n2\u533a\uff08\u4e1c\uff09\n\u9aa8\u79d1\uff08\u810a\u67f1\u3001\u5173\u8282\u3001\u521b\u4f24\u3001\u80bf\u7624\u3001\u624b\u8db3\uff09\n\n3\u533a\u4e1c\u5357\uff09\n\u795e\u7ecf\u5916\u79d1\u3001\u5fc3\u80f8\u5916\u79d1\u3001\u8840\u7ba1\u5916\u79d1\u3001\u6574\u5f62\u7f8e\u5bb9\u70e7\u4f24\u79d1\u3001\u7537\u79d1\n\n4\u533a\uff08\u5357\uff09\n\u5eb7\u590d\u533b\u5b66\u79d1\u3001\u75bc\u75db\u79d1\u3001\u6ccc\u5c3f\u5916\u79d1\u3001\u7537\u79d1\u68c0\u67e5\u5ba4\n\n5\u533a\u897f\u5357\uff09\n\u9aa8\u4ee3\u8c22\u75be\u75c5\u95e8\u8bca\u3001\u6ccc\u5c3f\u788e\u77f3\u3001\u8d85\u58f0\u8bca\u65ad\u79d1\uff08\u6ccc\u5c3fB\u8d85\uff09\n"
              }
            </div>
          </div>
          <div
            className={classNames(projectcss.all, sty.freeBox__ledA)}
            onClick={async event => {
              const $steps = {};

              $steps["goToPage"] = true
                ? (() => {
                    const actionArgs = {
                      destination: (() => {
                        try {
                          return (
                            $ctx.config.routePrefix +
                            "/Onthedayofadmissionthenursingteam"
                          );
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()
                    };
                    return (({ destination }) => {
                      if (
                        typeof destination === "string" &&
                        destination.startsWith("#")
                      ) {
                        document
                          .getElementById(destination.substr(1))
                          .scrollIntoView({ behavior: "smooth" });
                      } else {
                        __nextRouter?.push(destination);
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
              if (
                $steps["goToPage"] != null &&
                typeof $steps["goToPage"] === "object" &&
                typeof $steps["goToPage"].then === "function"
              ) {
                $steps["goToPage"] = await $steps["goToPage"];
              }
            }}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jwFvw
              )}
            >
              {"\u8fd4\u56de"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_124IntroductionToTheEnvironmentOfTheDay__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantsArgs;
    args?: Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames:
            Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgProps,
          internalVariantPropNames:
            Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_124IntroductionToTheEnvironmentOfTheDay__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_124IntroductionToTheEnvironmentOfTheDay";
  } else {
    func.displayName = `Plasmic_124IntroductionToTheEnvironmentOfTheDay.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"oGeya3WnsoRJC1KzKAMsFn"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "oGeya3WnsoRJC1KzKAMsFn"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const Plasmic_124IntroductionToTheEnvironmentOfTheDay = Object.assign(
  // Top-level Plasmic_124IntroductionToTheEnvironmentOfTheDay renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for Plasmic_124IntroductionToTheEnvironmentOfTheDay
    internalVariantProps:
      Plasmic_124IntroductionToTheEnvironmentOfTheDay__VariantProps,
    internalArgProps: Plasmic_124IntroductionToTheEnvironmentOfTheDay__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default Plasmic_124IntroductionToTheEnvironmentOfTheDay;
/* prettier-ignore-end */
