// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oGeya3WnsoRJC1KzKAMsFn
// Component: 4hqdijgZUH9F

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { Video } from "@plasmicpkgs/plasmic-basic-components";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: oGeya3WnsoRJC1KzKAMsFn/projectcss
import sty from "./Plasmic_48BalancedDietaryGuidelines.module.css"; // plasmic-import: 4hqdijgZUH9F/css

createPlasmicElementProxy;

export type Plasmic_48BalancedDietaryGuidelines__VariantMembers = {};
export type Plasmic_48BalancedDietaryGuidelines__VariantsArgs = {};
type VariantPropType = keyof Plasmic_48BalancedDietaryGuidelines__VariantsArgs;
export const Plasmic_48BalancedDietaryGuidelines__VariantProps =
  new Array<VariantPropType>();

export type Plasmic_48BalancedDietaryGuidelines__ArgsType = {};
type ArgPropType = keyof Plasmic_48BalancedDietaryGuidelines__ArgsType;
export const Plasmic_48BalancedDietaryGuidelines__ArgProps =
  new Array<ArgPropType>();

export type Plasmic_48BalancedDietaryGuidelines__OverridesType = {
  root?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  htmlVideo?: Flex__<typeof Video>;
};

export interface Default_48BalancedDietaryGuidelinesProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function Plasmic_48BalancedDietaryGuidelines__RenderFunc(props: {
  variants: Plasmic_48BalancedDietaryGuidelines__VariantsArgs;
  args: Plasmic_48BalancedDietaryGuidelines__ArgsType;
  overrides: Plasmic_48BalancedDietaryGuidelines__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          plasmic_plasmic_rich_components_css.plasmic_tokens,
          sty.root
        )}
        onClick={async event => {
          const $steps = {};

          $steps["goTo4NutritionKnowledge"] = true
            ? (() => {
                const actionArgs = { destination: `/Medication` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goTo4NutritionKnowledge"] != null &&
            typeof $steps["goTo4NutritionKnowledge"] === "object" &&
            typeof $steps["goTo4NutritionKnowledge"].then === "function"
          ) {
            $steps["goTo4NutritionKnowledge"] = await $steps[
              "goTo4NutritionKnowledge"
            ];
          }
        }}
      >
        <div className={classNames(projectcss.all, sty.freeBox__dCnh4)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__fLa5J
            )}
          >
            {"\u6587\u7ae0"}
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__sIwv)}>
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"25%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              onClick={async event => {
                const $steps = {};

                $steps["goToPage"] = true
                  ? (() => {
                      const actionArgs = {
                        destination: (() => {
                          try {
                            return $ctx.config.routePrefix + "/";
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return undefined;
                            }
                            throw e;
                          }
                        })()
                      };
                      return (({ destination }) => {
                        if (
                          typeof destination === "string" &&
                          destination.startsWith("#")
                        ) {
                          document
                            .getElementById(destination.substr(1))
                            .scrollIntoView({ behavior: "smooth" });
                        } else {
                          __nextRouter?.push(destination);
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["goToPage"] != null &&
                  typeof $steps["goToPage"] === "object" &&
                  typeof $steps["goToPage"].then === "function"
                ) {
                  $steps["goToPage"] = await $steps["goToPage"];
                }
              }}
              src={{
                src: "/plasmic/gu_lou_patient/images/资源162Xpng.png",
                fullWidth: 198,
                fullHeight: 198,
                aspectRatio: undefined
              }}
            />

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5VC4T
              )}
            >
              {"\u9000\u51fa"}
            </div>
          </div>
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__efSkA)}>
          <Video
            data-plasmic-name={"htmlVideo"}
            data-plasmic-override={overrides.htmlVideo}
            className={classNames("__wab_instance", sty.htmlVideo)}
            controls={true}
            src={
              "https://xiehe-1257043728.cos.ap-nanjing.myqcloud.com/dev/mp4/%E5%B9%B3%E8%A1%A1%E8%86%B3%E9%A3%9F%E6%8C%87%E5%8D%97.mp4"
            }
          />
        </div>
        <div className={classNames(projectcss.all, sty.freeBox__dZc9F)}>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__nABu
            )}
          >
            {"\u5e73\u8861\u81b3\u98df\u6307\u5357\uff1a"}
          </div>
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__skxYk
            )}
          >
            {
              "        \u5b9e\u73b0\u5408\u7406\u8425\u517b\uff0c\u5173\u952e\u5728\u4e8e\u901a\u8fc7\u79d1\u5b66\u7684\u81b3\u98df\u89c4\u5212\uff0c\u786e\u4fdd\u63d0\u4f9b\u6ee1\u8db3\u4eba\u4f53\u751f\u7406\u9700\u6c42\u7684\u80fd\u91cf\u548c\u5404\u7c7b\u8425\u517b\u7d20\u3002\u8fd9\u4e0d\u4ec5\u9700\u8981\u5173\u6ce8\u8425\u517b\u7d20\u7684\u79cd\u7c7b\u548c\u6570\u91cf\uff0c\u8fd8\u5e94\u8003\u8651\u98df\u7269\u7684\u642d\u914d\uff0c\u4ee5\u4fc3\u8fdb\u8425\u517b\u7269\u8d28\u7684\u6709\u6548\u6d88\u5316\u3001\u5438\u6536\u548c\u5229\u7528\u3002"
            }
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ttTy1)}>
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___0Vwha
              )}
            >
              {"\u8fd4\u56de"}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "htmlVideo"],
  img: ["img"],
  htmlVideo: ["htmlVideo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof PlasmicImg__;
  htmlVideo: typeof Video;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_48BalancedDietaryGuidelines__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_48BalancedDietaryGuidelines__VariantsArgs;
    args?: Plasmic_48BalancedDietaryGuidelines__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit< // Specify variants directly as props
    Plasmic_48BalancedDietaryGuidelines__VariantsArgs,
    ReservedPropsType
  > &
    /* Specify args directly as props*/ Omit<
      Plasmic_48BalancedDietaryGuidelines__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: Plasmic_48BalancedDietaryGuidelines__ArgProps,
          internalVariantPropNames:
            Plasmic_48BalancedDietaryGuidelines__VariantProps
        }),
      [props, nodeName]
    );
    return Plasmic_48BalancedDietaryGuidelines__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_48BalancedDietaryGuidelines";
  } else {
    func.displayName = `Plasmic_48BalancedDietaryGuidelines.${nodeName}`;
  }
  return func;
}

export const Plasmic_48BalancedDietaryGuidelines = Object.assign(
  // Top-level Plasmic_48BalancedDietaryGuidelines renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    htmlVideo: makeNodeComponent("htmlVideo"),

    // Metadata about props expected for Plasmic_48BalancedDietaryGuidelines
    internalVariantProps: Plasmic_48BalancedDietaryGuidelines__VariantProps,
    internalArgProps: Plasmic_48BalancedDietaryGuidelines__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default Plasmic_48BalancedDietaryGuidelines;
/* prettier-ignore-end */
